name: Genearate Changelog
on:
  workflow_dispatch: null

permissions:
  contents: write
  
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.TOKEN }}
      - name: Print outputs
        run: ${{ steps.changelog.outputs }}
        
      # Generate change log file using the script
      # - name: Generate Change Log
      #   uses: heinrichreimer/action-github-changelog-generator@v2.3
      #   with:
      #     token: ${{ secrets.TOKEN }} 
      
      # - name: Print changelog
      #   run: cat CHANGELOG.md
