name: Genearate Changelog
on:
  workflow_dispatch: null

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Generate change log file using the script
      - name: Generate Change Log
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.TOKEN }} 
      
      - name: Print changelog
        run: cat changelog.txt
