name: Conventional changelog
on:
  workflow_dispatch: null
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.TOKEN }}

      - name: Print outputs
        run: ${{ steps.changelog.outputs }}
